language: ruby
rvm:
  - 2.2.0
  - 2.5.5
  - 2.7.1

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_git.gemfile

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
